name: AutoNotify


on:
  schedule:
    - cron: "30 00 * * *" #  配置每天九点检测
  workflow_dispatch:

env:
  WEIXIN_WEBHOOK: ${{ secrets.WEIXIN_WEBHOOK }}
  WEIXIN_WEBHOOK1: ${{ secrets.WEIXIN_WEBHOOK1 }}
  MAIL: ${{ secrets.MAIL }}
  MAIL_PWD: ${{ secrets.MAIL_PWD }}
  MOBILE: ${{ secrets.MOBILE }}

jobs:
  Notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Run Project
        run: |
          npm install
          npm run notify
