name: AutoNotify
run-name: ${{ github.actor }} is testing

on:
  schedule:
    - cron: "30 00 * * *" #  配置每天九点检测
  workflow_dispatch:

env:
  WEIXIN_WEBHOOK: ${{ secrets.WEIXIN_WEBHOOK }}
  WEIXIN_WEBHOOK1: ${{ secrets.WEIXIN_WEBHOOK1 }}
  WEIXIN_WEBHOOK2: ${{ secrets.WEIXIN_WEBHOOK2 }}
  MAIL: ${{ secrets.MAIL }}
  MAIL_PWD: ${{ secrets.MAIL_PWD }}
  MOBILE: ${{ secrets.MOBILE }}
  MOBILE2: ${{ secrets.MOBILE2 }}
  COOKIE: ${{ secrets.COOKIE }}
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  Notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
      - name: Run Project
        run: |
          npm run notify
      - name: Upload version data
        uses: actions/upload-artifact@v2
        with:
          name: version-data
          path: cache/version_data.json  # 上传存储版本数据的文件
